CREATE TABLE IF NOT EXISTS roll (
  [TAX MAP PARCEL ID] TEXT,
  [CD] TEXT,
  [CURRENT OWNERS NAME] TEXT,
  [CURRENT OWNERS ADDRESS] TEXT,

   -- Like "4 SCHOOL LA"
  [PROPERTY LOCATION] TEXT,
   -- Like "210 1 FAMILY RES"
  [PROPERTY CLASS] TEXT,
  -- Like "SCARSDALE CENTRAL"
  [SCHOOL DISTRICT] TEXT,

  -- Raw
  [PARCEL SIZE/GRID COORD] TEXT,

  -- Clean
  [ACREAGE] INTEGER,
  [FRNT] INTEGER,
  [DPTH] INTEGER,
  [FULL MKT VAL] INTEGER,

  [LAND ASSESSMENT] INTEGER,
  [TOTAL ASSESSMENT] INTEGER,

  [COUNTY TAXABLE] INTEGER,
  [VILLAGE TAXABLE] INTEGER,
  [SCHOOL TAXABLE] INTEGER,

  [SEWER] TEXT,
  [SOLID WASTE] TEXT
);
